from zvtm.domain import Block,BlockStock,Block1dKdata,Block1wkKdata,Block1monKdata,Block1mKdata,Index1mKdata,Index1dKdata
# Block.record_data(provider="eastmoney")
# BlockStock.record_data(provider="eastmoney")
# Block.record_data(provider="em")
# BlockStock.record_data(provider="em")
Block1dKdata.record_data(provider="em")
# Block1wkKdata.record_data(provider="em")
# Block1monKdata.record_data(provider="em")
# Block1mKdata.record_data(provider="em")
# Index1mKdata.record_data(provider='joinquant',code='000001')
# Index1dKdata.record_data(provider='em',code='000001')